# Declarative package set for macOS, applied by macos.sh via `brew bundle`.
brew "git"
brew "tmux"
brew "python3"
brew "thefuck"
brew "direnv"
brew "neovim"
brew "node"
brew "ruby"
brew "fd"
brew "ripgrep"
brew "fzf"
brew "unzip"
brew "zip"
brew "wget"
cask "font-jetbrains-mono-nerd-font"
